# Usar la imagen base Ubuntu 24.10
FROM ubuntu:24.10

WORKDIR /apl

RUN apt-get update && apt-get install -y \
    g++ \
    make \
    libpthread-stubs0-dev \
    && apt-get clean

# Copia los archivos del proyecto al contenedor
COPY ./ /apl/

# # Compila cada ejercicio
# RUN cd Ejercicio1 && make
# RUN cd Ejercicio2 && make
# RUN cd Ejercicio3 && make
# RUN cd Ejercicio4 && make // aca rompia - estan dentro de otro subdirectorio
# RUN cd Ejercicio5 && make

# para mantener el contenedor activo
CMD ["bash"]